### PR TITLE
Added second way of extension initialization. 

### PR DESCRIPTION
**Pull request by gunlinux**
Added second way of extension  initialization. In standardization of flask extensions.

Better way for app fabric too

### CODE REVIEW

**Comment by vindarel** [comment]
Hi, does this PR fix something, does it allow to `import flask_markdown` instead of `flask.ext` ? thanks

**Comment by gunlinux** [comment]
Yes It is

**Comment by Demian87** [comment]
Who can fix CI?

**Comment by gunlinux** [comment]
I have a copy-paste issue in desc, using SQLAlchemy module in desc of usage.  But ci is fixes.

I wasn't in dev few years, great lib is it on core my blog engine.

**Comment by gunlinux** [comment]
Double https://github.com/dcolish/flask-markdown/pull/20

**Pull request closed without merging**
