### PR TITLE
Make work with app factory pattern

### PR DESCRIPTION
**Pull request by colmjude**
I've updated the class to work with the flask app factory pattern.

### CODE REVIEW

**Comment by Demian87** [comment]
@dcolish Please, merge it. It's pretty handy.

**Comment by Frick-David** [comment]
This app does not appear to have seen development in years. You might want to fork the project and then go from there. It is a shame Python, or Flask do not do something about this.

**Comment by dcolish** [comment]
This project was rejected by the flask project for listing years ago. I’m glad you’ve found it useful. I do  it currently support it so if you’re interested in taking it over I’m happy to help with the transition.

**Comment by undergrinder** [comment]
I am learning Flask right now. I find this extension and this commit very handy. Thank you!

**Comment by dcolish** [comment]
Oh dang. I’m sorry I held this up so long. I just never gave it min full attention. This is fine. LGTM. Please help me find a maintainer if you find this code useful.

**Pull request merged**
